/** Curated suggestions for job postings; users can still add any custom skill. */
export const JOB_SKILL_SUGGESTIONS: string[] = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Django",
  "FastAPI",
  "Go",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Git",
  "REST APIs",
  "GraphQL",
  "System design",
  "Microservices",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "UI/UX",
  "Figma",
  "Product management",
  "Agile",
  "Scrum",
  "Data analysis",
  "Machine learning",
  "TensorFlow",
  "PyTorch",
  "Cybersecurity",
  "DevOps",
  "Linux",
  "Mobile development",
  "React Native",
  "Swift",
  "Kotlin",
  "Communication",
  "Leadership",
];
