services:
  job-platform-api:
    container_name: job-platform-api-dev
    image: job-platform-api:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/job-platform-api
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:5.0
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  rabbitmq-data:
